# Site settings
title: GeoKrety Map
email: contact@geokretymap.org
description: >
  World Map of GeoKrety, and tutorials on how to log GeoKrety.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://geokretymap.org" # the base hostname & protocol for your site
github_username:  GeoKretyMap

# Build settings
markdown: kramdown
